### ISSUE TITLE
Are you sure using time shifting sampling schedule technology (from Esser et al., 2024b) in you sample algorithm?

### ISSUE THREAD

**Issue by lllzzz3** [UNITES-Lab/FlowTS#1]
I cannot find time shifting sampling schedule technology in you code .

**Comment by yanghu819** [comment]
https://github.com/UNITES-Lab/FMTS/blob/b538333c3f7c85195748d7260011f5418071a15f/FMTS/Models/interpretable_diffusion/FMTS.py#L61
here

**Comment by lllzzz3** [comment]
all right, this time shifting sampling schedule technology is used in unconditional sample algorithm. I thought it would be used during conditional sampling. It's my mistaken thought.

**Comment by yanghu819** [comment]
conditional sampling uses the t-power sampling，
https://github.com/UNITES-Lab/FMTS/blob/b538333c3f7c85195748d7260011f5418071a15f/FMTS/Models/interpretable_diffusion/FMTS.py#L122C1-L123C1
